name: help_me_mitra_alpha_ver
description: "HelpMe! Alpha Development Version - Mitra App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.7.0
  email_validator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_chat_ui: ^1.6.15
  flutter_native_splash: ^2.4.1
  flutter_randomcolor: ^1.0.15
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  flutter_osm_plugin: ^1.3.3+1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  shared_preferences: ^2.3.2
  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
