name: help_me_mitra_alpha_ver
description: "HelpMe! Alpha Development Version - Mitra App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.4.1
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.3
  flutter_native_splash: ^2.4.1
  flutter_osm_plugin: ^1.3.3+1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  http_parser: ^4.0.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  mime: ^1.0.6
  path: ^1.9.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
